context:
  version: 0.1.0

package:
  name: pug-lsp
  version: ${{ version }}

source:
  url: https://github.com/opa-oz/pug-lsp/archive/v${{ version }}.tar.gz
  sha256: 88a9723b25794d311e1221f404b30e3f9e8dcab80782f04e7d2ead5ebf567f16

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('go-cgo') }}
    - go-licenses

tests:
  - script: |
      pug-lsp &
      exe_pid=$!
      trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: An implementation of the Language Protocol Server for Pug.js
  homepage: https://github.com/opa-oz/pug-lsp
  repository: https://github.com/opa-oz/pug-lsp

extra:
  recipe-maintainers:
    - danielnachun
